apiVersion: 1

datasources:
  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger-query:16686
    uid: jaeger
    isDefault: false
    editable: true
    jsonData:
      tracesToLogs:
        # Correlate traces to logs in Loki
        datasourceUid: 'loki'
        tags: ['trace_id']
        mappedTags: [{ key: 'service.name', value: 'app' }]
        mapTagNamesEnabled: true
        spanStartTimeShift: '-1m'
        spanEndTimeShift: '1m'
        filterByTraceID: true
      tracesToMetrics:
        # Correlate traces to metrics in Prometheus
        datasourceUid: 'prometheus'
        tags: [{ key: 'service.name', value: 'app' }]
        queries:
          - name: 'Request rate'
            query: 'rate(cap_verifier_requests_total{app="$__tags"}[5m])'
          - name: 'Error rate'
            query: 'rate(cap_verifier_requests_total{app="$__tags",result="fail"}[5m])'
      nodeGraph:
        enabled: true
