apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: false
    editable: true
    jsonData:
      maxLines: 1000
      derivedFields:
        # Link logs to traces (trace_id correlation)
        - datasourceUid: jaeger
          matcherRegex: '"trace_id":"(\w+)"'
          name: TraceID
          url: '$${__value.raw}'
        # Link logs to Prometheus metrics
        - datasourceUid: prometheus
          matcherRegex: '"container":"([^"]+)"'
          name: Container
          url: '/explore?left=["now-1h","now","Prometheus",{"expr":"{container=\"$${__value.raw}\"}"}]'
